previsionnel:
    resource: "@PrevisionnelBundle/Resources/config/routing.yml"
    prefix:   /

previsionnel_user:
    resource: "@PrevisionnelUserBundle/Resources/config/routing.yml"
    prefix:   /

previsionnel_tickets:
    resource: "@mawaceticketBundle/Resources/config/routing.yml"
    prefix:   /
    
mawace_page_professeur:
    resource: "@MAWACEPageProfBundle/Resources/config/routing.yml"
    prefix:   /
    
mawace_tickets:
    resource: "@mawaceticketBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: PrevisionnelUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

previsionneluser_accueil:
    path: /accueil
    defaults:
        _controller: PrevisionnelUserBundle:Accueil:index