previsionnel:
    resource: "@PrevisionnelBundle/Resources/config/routing.yml"
    prefix:   /

mawace_page_professeur:
    resource: "@MAWACEPageProfBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
