previsionnel_prevision:
    path:     /prevision
    defaults: { _controller: PrevisionnelBundle:Prevision:index }

previsionnel_search_utilisateurs:
    path:     /prevision/search-utilisateurs
    defaults: { _controller: PrevisionnelBundle:Prevision:searchUtilisateurs }

previsionnel_get_utilisateurs:
    path:     /prevision/get-utilisateurs/{id}
    defaults: { _controller: PrevisionnelBundle:Prevision:getUtilisateurs }

previsionnel_search_ue:
    path:     /prevision/search-ue
    defaults: { _controller: PrevisionnelBundle:Prevision:searchUe }

previsionnel_get_ue:
    path:     /prevision/get-ue/{id}
    defaults: { _controller: PrevisionnelBundle:Prevision:getUe }

previsionnel_search_typecours:
    path:     /prevision/search-typecours
    defaults: { _controller: PrevisionnelBundle:Prevision:searchTypecours }

previsionnel_get_typecours:
    path:     /prevision/get-typecours/{id}
    defaults: { _controller: PrevisionnelBundle:Prevision:getTypecours }
    
secretaire_homepage:
    path:     /secretaire
    defaults: { _controller: PrevisionnelBundle:Secretaire:index }
    

previsionnel_departement:
    path: /departement
    defaults: { _controller: PrevisionnelBundle:Departement:index}

previsionnel_search_departement:
    path:     /prevision/search-departement
    defaults: { _controller: PrevisionnelBundle:Departement:searchDepartement }

previsionnel_get_departement:
    path:     /prevision/get-departement/{id}
    defaults: { _controller: PrevisionnelBundle:Departement:getDepartement }


previsionnel_coefficients:
    path:     /coefficients
    defaults: { _controller: PrevisionnelBundle:Coefficients:coefficients }

previsionnel_search_statut:
    path:     /coefficients/search-statut
    defaults: { _controller: PrevisionnelBundle:Coefficients:searchStatut }

previsionnel_get_statut:
    path:     /coefficients/get-statut/{id}
    defaults: { _controller: PrevisionnelBundle:Coefficients:getStatut }