<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * coefficientsnormauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coefficientsnormauxRepository extends \Doctrine\ORM\EntityRepository
{
}
