<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * coefficientssupplementairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coefficientssupplementairesRepository extends \Doctrine\ORM\EntityRepository
{
}
