<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * departementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class departementsRepository extends \Doctrine\ORM\EntityRepository
{
}
