<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * heuresaffecteesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class heuresaffecteesRepository extends \Doctrine\ORM\EntityRepository
{
}
