<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * statutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statutRepository extends \Doctrine\ORM\EntityRepository
{
}
