<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * typecoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typecoursRepository extends \Doctrine\ORM\EntityRepository
{
}
