<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * ueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ueRepository extends \Doctrine\ORM\EntityRepository
{
}
