<?php

namespace MAWACE\PageProfBundle\Repository;

/**
 * utilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateursRepository extends \Doctrine\ORM\EntityRepository
{
}
